# -*- coding: utf-8 -*-
"""CHROMA_VS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GaAL4xU-5BGXF0QTkXFsom_7vcEy3LSj
"""

!pip install langchain-huggingface

pip install -U langchain-community

!pip install -U langchain-chroma chromadb

import os
from google.colab import userdata
from langchain_huggingface import HuggingFaceEmbeddings
from langchain.vectorstores import Chroma
from langchain.schema import Document

# Step 1: Load Hugging Face token securely from Colab secrets
hf_token = userdata.get("HF_TOKEN")
assert hf_token and hf_token.startswith("hf_"), "HF_TOKEN missing in Colab secrets!"
os.environ["HUGGINGFACEHUB_API_TOKEN"] = hf_token

import os

os.environ["HUGGINGFACEHUB_API_TOKEN"] = hf_token  # Set token in environment

embedding_function = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
    # no huggingfacehub_api_token argument here
)

import os

os.environ["HUGGINGFACEHUB_API_TOKEN"] = hf_token  # Set your HF token here

embedding_function = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
    # NO huggingfacehub_api_token argument here
)

# Step 3: Create Chroma vector store with HuggingFace embeddings
vector_store = Chroma(
    embedding_function=embedding_function,
    persist_directory="my_chroma_db",
    collection_name="sample"
)

# Step 4: Create your LangChain Document objects with metadata
docs = [
    Document(page_content="Virat Kohli is one of the most successful and consistent batsmen in IPL history. Known for his aggressive batting style and fitness, he has led the Royal Challengers Bangalore in multiple seasons.", metadata={"team": "Royal Challengers Bangalore"}),
    Document(page_content="Rohit Sharma is the most successful captain in IPL history, leading Mumbai Indians to five titles. He's known for his calm demeanor and ability to play big innings under pressure.", metadata={"team": "Mumbai Indians"}),
    Document(page_content="MS Dhoni, famously known as Captain Cool, has led Chennai Super Kings to multiple IPL titles. His finishing skills, wicketkeeping, and leadership are legendary.", metadata={"team": "Chennai Super Kings"}),
    Document(page_content="Jasprit Bumrah is considered one of the best fast bowlers in T20 cricket. Playing for Mumbai Indians, he is known for his yorkers and death-over expertise.", metadata={"team": "Mumbai Indians"}),
    Document(page_content="Ravindra Jadeja is a dynamic all-rounder who contributes with both bat and ball. Representing Chennai Super Kings, his quick fielding and match-winning performances make him a key player.", metadata={"team": "Chennai Super Kings"}),
]

# Step 5: Add documents to your Chroma vector store
vector_store.add_documents(docs)

# Step 6: Run a similarity search on the vector store
results = vector_store.similarity_search(query="Who among these are a bowler?", k=2)
for doc in results:
    print(f"Team: {doc.metadata['team']}")
    print(f"Content: {doc.page_content}\n")

# Optional: Search with scores
results_scores = vector_store.similarity_search_with_score(query="Who among these are a bowler?", k=2)
for doc, score in results_scores:
    print(f"Score: {score:.4f}")
    print(f"Team: {doc.metadata['team']}")
    print(f"Content: {doc.page_content}\n")

# update documents
updated_doc1 = Document(
    page_content="Virat Kohli, the former captain of Royal Challengers Bangalore (RCB), is renowned for his aggressive leadership and consistent batting performances. He holds the record for the most runs in IPL history, including multiple centuries in a single season. Despite RCB not winning an IPL title under his captaincy, Kohli's passion and fitness set a benchmark for the league. His ability to chase targets and anchor innings has made him one of the most dependable players in T20 cricket.",
    metadata={"team": "Royal Challengers Bangalore"}
)

vector_store.update_document(document_id='09a39dc6-3ba6-4ea7-927e-fdda591da5e4', document=updated_doc1)

# view documents
vector_store.get(include=['embeddings','documents', 'metadatas'])

